name: Build installer image

on:
  workflow_dispatch:
    inputs:
      profile:
        type: string
        description: ""
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Use service account token
        run: |
          echo "OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}" >> "$GITHUB_ENV"
      
      - name: Retrieve secureboot components
        run: |
          mkdir secureboot

          op read op://${{ secrets.SECUREBOOT_OP_PK_KEY_REF }} -o secureboot/PK.pkcs1.key > /dev/null
          op read op://${{ secrets.SECUREBOOT_OP_PK_CERT_REF }} -o secureboot/PK.crt > /dev/null

          op read op://${{ secrets.SECUREBOOT_OP_PCR_KEY_REF }} -o secureboot/PCR.pkcs1.key > /dev/null

          op read op://${{ secrets.SECUREBOOT_OP_PK_AUTH_REF }} -o secureboot/PK.auth > /dev/null
          op read op://${{ secrets.SECUREBOOT_OP_KEK_AUTH_REF }} -o secureboot/KEK.auth > /dev/null
          op read op://${{ secrets.SECUREBOOT_OP_DB_AUTH_REF }} -o secureboot/db.auth > /dev/null
      
      - uses: cue-lang/setup-cue@v1.0.1
        with:
          version: "v0.12.1"

      - name: Retrieve profile Talos version
        id: talos-version
        run: echo "version=$(cue eval -e version --out text)" >> "$GITHUB_OUTPUT"

      - name: Build installer image
        run: |
          ls -a
          mkdir _out
          cue export ${{ inputs.profile }} --out yaml | docker run --rm -i -v $(pwd)/secureboot:/secureboot:ro -v $(pwd)/_out:/out ghcr.io/siderolabs/imager:${{ steps.talos-version.outputs.version }} -
