name: Build installer image for profile

on:
  workflow_call:
    inputs:
      profile:
        type: string
        description: ""
        required: true

env:
  REGISTRY: "ghcr.io/remi-gelinas/talos-installer"

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f # v1

      - name: Retrieve secureboot components
        env:
          OP_SERVICE_ACCOUNT_TOKEN: "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}"
        run: |
          mkdir secureboot

          op read op://${{ secrets.SECUREBOOT_OP_PK_KEY_REF }} -o secureboot/PK.pkcs1.key > /dev/null
          op read op://${{ secrets.SECUREBOOT_OP_PK_CERT_REF }} -o secureboot/PK.crt > /dev/null

          op read op://${{ secrets.SECUREBOOT_OP_PCR_KEY_REF }} -o secureboot/PCR.pkcs1.key > /dev/null

          op read op://${{ secrets.SECUREBOOT_OP_PK_AUTH_REF }} -o secureboot/PK.auth > /dev/null
          op read op://${{ secrets.SECUREBOOT_OP_KEK_AUTH_REF }} -o secureboot/KEK.auth > /dev/null
          op read op://${{ secrets.SECUREBOOT_OP_DB_AUTH_REF }} -o secureboot/db.auth > /dev/null
      
      - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
      
      - name: Extract build info
        id: build-info
        run: |
          echo "talos-version=$(cue eval ${{ inputs.profile }} -e version --out text)" >> "$GITHUB_OUTPUT"
          echo "short-sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "profile-name=$(cue eval ${{ inputs.profile }} -e '#profile.name' --out text)" >> "$GITHUB_OUTPUT"

      - name: Build installer image
        run: |
          mkdir _out
          cue export ${{ inputs.profile }} --out yaml | docker run --rm -i -v $(pwd)/secureboot:/secureboot:ro -v $(pwd)/_out:/out ghcr.io/siderolabs/imager:${{ steps.build-info.outputs.talos-version }} -
      
      - name: Install crane
        uses: iarekylew00t/crane-installer@742c36c852cb03df7b947b37aff0b65ead86f49e # v3

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Push image to registry
        id: push-image
        run: |
          ARTIFACT=$(cue eval ${{ inputs.profile }} -e "#profile.artifact" --out text)
          echo "digest=$(crane digest --tarball _out/$ARTIFACT)" >> "$GITHUB_OUTPUT"
          crane push _out/$ARTIFACT ${{ env.REGISTRY }}/${{ steps.build-info.outputs.profile-name }}:${{ steps.build-info.outputs.talos-version }}-${{ steps.build-info.outputs.short-sha }}
          
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ steps.build-info.outputs.profile-name }}
          subject-digest: ${{ steps.push-image.outputs.digest }}
          push-to-registry: true
